version: '3'

services:
  # db:
  #   image: postgres:13.0
  #   container_name: db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=test
  #   volumes:
  #     - .\dump.sql:/docker-entrypoint-initdb.d/10-dump.sql
  #   networks:
  #     custom_net:
  #       ipv4_address: 172.10.1.2
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  strapi:
    build:
      context: ./Strapi
    container_name: strapi
    networks:
      custom_net:
        ipv4_address: 172.10.1.3

  landing:
    build:
      context: ./Landing
      dockerfile: Dockerfile
    container_name: landing
    ports:
      - "3000:3000"
    networks:
      custom_net:
        ipv4_address: 172.10.1.4
    depends_on:
      - strapi

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl-test/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl-test/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    environment:
      - DOMAIN_NAME=REPLACE_ME
    networks:
      custom_net:
        ipv4_address: 172.10.1.5
    depends_on:
      - strapi
      - landing

networks:
  custom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
          gateway: 172.10.1.1
